mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
mode: Rule
bind-address: "*"
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: error
find-process-mode: always
global-client-fingerprint: random
external-controller: 0.0.0.0:9090
secret: ""
external-ui: ./dashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "+.douyinpic.com"
    - "+.douyincdn.com"
    - "+.amemv.com"

tun:
  enable: false
  device: meta
  stack: mixed
  dns-hijack: [any:53, tcp://any:53]
  udp-timeout: 300
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  use-hosts: true
  fake-ip-range: 192.18.0.1/16
  fake-ip-filter:
    - "*.lan"
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://cloudflare-dns.com/dns-query#DNS
    - https://dns.google/dns-query#DNS

proxies:
  - { name: DNS_Hijack, type: dns }

proxy-groups:
  - name: 国内直连
    type: select
    proxies: [DIRECT, REJECT]
    icon: https://gitlab.com/akikawa/backup/-/raw/main/IconSet/Color/China.png

  - name: 漏网之鱼
    proxies: [REJECT, 国内直连, REJECT-DROP, PASS]
    icon: https://gitlab.com/akikawa/backup/-/raw/main/IconSet/Color/Final.png

rules:
  - MATCH,漏网之鱼
